ALTER TABLE "production_items" ADD COLUMN "hook" text;--> statement-breakpoint
ALTER TABLE "production_items" ADD COLUMN "hook_source" text;--> statement-breakpoint
ALTER TABLE "production_items" ADD COLUMN "hook_extractor" text;--> statement-breakpoint
ALTER TABLE "production_items" ADD COLUMN "hook_extracted_at" timestamp with time zone;--> statement-breakpoint
CREATE INDEX "idx_production_items_hook_pending" ON "production_items" USING btree ("status","hook_extracted_at");--> statement-breakpoint
-- Backfill hook from clip_ideas for items that were promoted from a triaged
-- clip idea. Zero-cost: the clip_ideas.hook was already generated by the
-- clip-idea agent with explicit verbatim-from-transcript instructions, so
-- it's higher-quality than any re-extraction would produce. hook_source
-- 'clip_idea' is never re-extracted by the sweep.
UPDATE "production_items" pi
SET "hook" = ci."hook",
    "hook_source" = 'clip_idea',
    "hook_extracted_at" = now()
FROM "clip_ideas" ci
WHERE pi."source_clip_idea_id" = ci."id"
  AND pi."hook" IS NULL;